####bioMod Function    ####
####Re-Script Sept 2017####
###########################

bioMod <- function(mod.id, occ.db, nrep = 5, run.id, dbl = T,...){
  ## Function for running Biomod modeling on the birthing of African bats
  ## Arguments:
  ## mod.id <- model identifictation, generally list item from listGen()
  ## occ.df <- occurence dataframe generated by occLoad or occLoad2
  ## nrep <- number of model runs to preform
  ## mod.id <- name string for model run id
  
  #### Directories and Logs ####
  out.dir <- outDirGen(run.id = run.id, mod.id = mod.id) #create output dir
  ## Start log file
  out.log <- log.path(path.to.dir = out.dir, run.id = run.id, mod.id = mod.id)
  cat("Model Run: ", run.id, " Item: ", mod.id, "\nStart ", date(), "\n",
      file = out.log, fill = T)
  
  #### Occurrence and Co-varriates ####
  myResp <- as.numeric(occ.db[,mod.id])
  myRespxy <- occ.db[,1:2]
  
  ## Co-varriates
  static.stk <- staticStkLoad(path.to.dir = clean.dir)
  ifelse(dbl = T,
  tempo.stk <- stkRevolver2(month = mod.id, path.to.dir = norm.dir),
  tempo.stk <- stkRevolver(month = mod.id, path.to.dir = norm.dir))
  
  
  env <- do.call(stack, c(static.stk, tempo.stk))
  
  env.rotate <- envPCA(env = env, mod.id = mod.id, path.to.dir = out.dir)
   ## Needs Occurence weights vector ##
  #### Format Data ####
  myBiomodData <- BIOMOD_FormatingData(resp.var = myResp,
                                       expl.var = env.rotate,
                                       resp.xy = myRespXY,
                                       resp.name = mod.id)
  ## Send to Log
  cat(capture.output(myBiomodData), file = out.log, fill=T, append = T)
  cat("Begin Modeling ", date(), "\n", file = out.log, fill = T, append = T)
  
  #### Options #####
  myBiomodOption <- BIOMOD_ModelingOptions(MAXENT.Phillips = list(path_to_maxent.jar = getwd(),
                                                                  memory_allocated = 7168,
                                                                  maximumiterations = 1000))
  ## Send to log
  cat(capture.output(myBiomodOption), file = out.log, fill = T, append = T)
  #### Modeling ####
  myBiomodModelOut <- BIOMOD_Modeling(myBiomodData,
                                      models = c('GLM','GBM','CTA','ANN',
                                                 'SRE','FDA','RF','MAXENT.Phillips', 
                                                 "MAXENT.Tsuruoka"),
                                      models.options = myBiomodOption,
                                      NbRunEval= nrep,
                                      DataSplit=70,
                                      Yweights = weights, #### NEEDS ATTENTION 
                                      VarImport= nrep,
                                      models.eval.meth ='ROC',
                                      SaveObj = TRUE,
                                      rescal.all.models = FALSE,
                                      do.full.models = TRUE,
                                      modeling.id = paste0(mod.id, run.id))
  
  ## Save models evaluation and variables importance 
  BioModEval <- get_evaluations(myBiomodModelOut,as.data.frame=T)
  write.csv(BioModEval, 
            file.path(outdir, paste0(mod.id,"_All_Model_Eval.csv")),row.names = F)
  
  varImportance <- normImp(myBiomodModelOut)
  write.csv(varImportance, 
            file.path(outdir, paste0(mod.id,"_All_Model_VarImp.csv")),row.names = F)
  
  ## Send to log
  cat("Preliminary Models Built at: ", date(), "\n", file = out.log, fill = T, append = T)
  cat(capture.output(myBiomodModelOut),file = out.log, fill = T, append = T)
  
  #### Ensemble modeling ####
  
  ##Chek which models succeded and model all of those 
  succeded <- setdiff(myBiomodModelOut@models.computed, myBiomodModelOut@models.failed)
  
  myBiomodEM <- BIOMOD_EnsembleModeling(
    modeling.output = myBiomodModelOut,
    chosen.models = succeded,
    em.by='all',
    eval.metric = 'all',
    eval.metric.quality.threshold = NULL,
    prob.mean = T,
    prob.cv = F,
    prob.ci = F,
    prob.ci.alpha = F,
    prob.median = T,
    committee.averaging = T,
    prob.mean.weight = T,
    prob.mean.weight.decay = 'proportional',
    VarImport = nrep)
  
  ## Save models evaluation and variables importance
  EM.eval <- get_evaluations(myBiomodEM, as.data.frame=T)
  write.csv(EM.eval, file.path(outdir,paste0(mod.id,"_EM_Eval.csv")), row.names = F)
  EM.var <- ensVarEval(myBiomodEM,n=nrep)
  write.csv(EM.var, file.path(outdir,paste0(mod.id,"_EM_VarImp.csv")))
  
  ## Send to Log
  cat("Ensamble Built at: ", date(),"\n", 
      capture.output(myBiomodEM), "\nProjection Start",
      file = out.log, fill = T, append = T)
  
  #### Projection ####
  myBiomodProj <- BIOMOD_Projection(
    modeling.output = myBiomodModelOut,
    new.env = env.rotate,
    proj.name = mod.id,
    selected.models = succeded,
    binary.meth = NULL,
    compress = 'gzip',
    build.clamping.mask = F,
    ommit.na = T,
    output.format = '.grd')
  
  ## Send to log
  cat("\nProjection Built at: ", date(), "\n",capture.output(myBiomodProj),
      "\nEnsemble Projection Start\n",
      file=out.log, fill = T, append = T)
  


  #### Ensemble Projection ####
  myBiomodEF <- BIOMOD_EnsembleForecasting(
    Em.output = myBiomodEM,
    projection.output = myBiomodProj,
    EM.output = myBiomodEM,
    proj.name = paste0(mod.id,"ENSEMBLE_PROJ"))
  
  ## Send to log
  cat("Emsemble Projection Built at: ", date(), "\n#Shitsfinished",
      file = out.log, append = T)
  
}