##Occ Smash
  #Script for creating dataframes representing the binary breeding of African Bats
  # Update of BioOccMunge
##See if cached files exist in the clean.dir
taxa <- c("mic", "mol", "ptr")
exist.names <- paste0(taxa,"Occ.csv")

if(file.exists(file.path(clean.dir, exist.names))){
  taxa <- c("mic", "mol", "ptr")
  for( i in 1:3){
    assign(paste0(taxa[[i]], ".occ"),
           read.csv(file.path(clean.dir, paste0(taxa[[i]],"Occ.csv"))))
  }
  rm(taxa)
} else{
  biGen <- function(x){
    ### Funtion to create monthly occurrence/absence vectors for each record ###
    ## Argument: x - dataframe of events with location and breeding record
    empty <- as.data.frame(matrix(nrow=nrow(x), ncol=12)) 
    for(i in 1:nrow(empty)){
      for(j in 1:ncol(empty)){
        ifelse(j >= x[i,]$Start &  x[i,]$End >= j,empty[i,j]<-1,empty[i,j]<-0)
      }}
    names(empty) <- paste0("Birth",seq(1:12))
    out <- cbind(x,empty)
    return(out)
  }
  occGen <- function(df,name){
    ### Function to rasterize locations and generate monthly Occurrence/Absence dataframes ###
    ### Includes a 50Km buffer around each point to account for potential inpersion in source data.
    ## Arguments: 
    ## df - dataframe generated by biGen()
    ## name - character string for naming purposes
    coordinates(df) <- ~Lon + Lat
    proj4string(df) <- projection(wgs)
    df.e <- spTransform(df, CRS( "+init=epsg:3347" ))
    df.b <- gBuffer(df.e, width = 50000, byid = T)
    df.t <- spTransform(df.b, CRS(wgs))
    out <- data.frame()
    for(i in 1:12){
      rr1 <- rasterize(df.t,rf.mask, field= df.t[[paste0("Birth",i)]], fun=max)
      rr2 <- crop(rr1,rf.mask)
      rr3 <- mask(rr2,rf.mask)
      df1 <- xyFromCell(rr3, cell = which(!is.na(rr3[])))
      df2 <- as.data.frame(cbind(df1,raster::extract(rr3,df1)))
      ifelse(i == 1, out <- df2, out <- as.data.frame(cbind(out,df2[,3])))
      colnames(out) <- c(colnames(out[,-ncol(out)]),paste0(name,i))
    }
    
    return(out)
  }
  #### Occurrence/Absence ####
  library(dplyr)
  #Read Complete dataframe
  dat <- read.csv(file.path("data", "afrBatBirthDB.csv"))
  
  #Subset into classes from Cummings and Bernard 1997
  ptr <- filter(dat, Class==1)
  mol <- filter(dat, Class==2)
  mic <- filter(dat, Class==3)
  
  #### Dataframes with binary vectors ####
  ptr.bi <- biGen(ptr)
  mol.bi <- biGen(mol)
  mic.bi <- biGen(mic)
  
  ####Spatial Bits ####
  ## Creating Occurrence/Absence dataframes for each month and location
  rf.mask <- raster(file.path(data.source, "cropMask.tif")) ## Croping mask used for this project (see GeoSmash.R)
  wgs <- proj4string(rf.mask)
  
  library(dismo);library(rgeos)
  
  ####Dataframes summarizing Occurrence/Absence at each location####
  ptr.occ <- occGen(ptr.bi, "ptr")
  mol.occ <- occGen(mol.bi, "mol")
  mic.occ <- occGen(mic.bi, "mic")
  
  ####Write Dataframes####
  write.csv(ptr.occ, file = file.path(clean.dir,"ptrOcc.csv"), row.names = F)
  write.csv(mol.occ, file = file.path(clean.dir,"molOcc.csv"),row.names = F)
  write.csv(mic.occ, file = file.path(clean.dir,"micOcc.csv"),row.names = F)
  
  rm(dat, mic, mic.bi, mol, mol.bi, ptr, ptr.bi)
}
