#### Viral Occurrence Munge ####
#### Re-work Oct 2017       ####
################################

source("R/helperFunctions.R")
library(rgdal);library(rgeos);library(raster);library(dplyr)

 ##Virus OCC functions
biGenV <- function(x){
  ### Funtion to create monthly occurrence/absence vectors for each record ###
  ## Argument: x - dataframe of events with location and breeding record
  empty <- as.data.frame(matrix(nrow=nrow(x), ncol=12)) 
  for(i in 1:nrow(empty)){
    for(j in 1:ncol(empty)){
      ifelse(j == x[i,]$"Month.Start",empty[i,j]<-1,empty[i,j]<-0)
    }}
  names(empty) <- paste0("OB",seq(1:12))
  out <- cbind(x,empty)
  return(out)
}

occGenV <- function(df, name, mask){
  ### Function to rasterize locations and generate monthly Occurrence/Absence dataframes ###
  ### Includes a 50Km buffer around each point to account for potential inpersion in source data.
  ## Arguments: 
  ## df - dataframe generated by biGenV()
  ## name - character string for naming purposes
  ## mask - name of the mask used
  coordinates(df) <- ~ x + y
  proj4string(df) <- proj4string(mask)
  out <- data.frame()
  for(i in 1:12){
    rr1 <- rasterize(df,mask, field= df[[paste0("OB",i)]], fun='count')
    rr2 <- crop(rr1,mask)
    rr3 <- mask(rr2,mask)
    df1 <- xyFromCell(rr3, cell = which(!is.na(rr3[])))
    df2 <- as.data.frame(cbind(df1,raster::extract(rr3,df1)))
    ifelse(i == 1, out <- df2, out <- as.data.frame(cbind(out,df2[,3])))
    colnames(out) <- c(colnames(out[,-ncol(out)]),paste0(name,i))
  }
  
  return(out)
}

## 
c.mask <- raster(file.path(data.source, "cropMask.tif"))
wgs <- proj4string(c.mask)

#### human index cases ####
 ## note : bring in the Human_Index_30May. Contains 1 additional point over
 ## the source dataframe provided representing the Inkanamo outbreak
hum.src <- read.csv(file.path(data.source, "vIndex", "Human_Index_30May.csv"))
hum.simple <- hum.src %>% dplyr::select(Outbreak_ID, Virus, Month.Start, Month.Start, Month.End , Class)
  
  #### Polygons ####
hum.poly <- readOGR(file.path(data.source, "vIndex", "humanORG"), 
                    "index_human_case_modified_polygon")

 ## Extract centroids but maintain the data from the origina; obj
hum.poly.c <- SpatialPointsDataFrame(gCentroid(hum.poly, byid = T),
                                     hum.poly@data, match.ID = F)
  #### Points ####
 ## Still needs to be added here
hum.pts <- readOGR(file.path(data.source, "vIndex", "humanORG"), 
                   "index_human_case_modified_point")
new <- c(-0.616667, 20.433333, 31, 20.433333, -0.616667)
human.add <- rbind(as.data.frame(hum.pts), new)
coordinates(human.add) <- ~ coords.x1 + coords.x2
proj4string(human.add) <- CRS(wgs)
 ## Remove the lat and long cols
hum.add <- human.add[,3]

  #### masterFrame ####
hu.ma <- rbind(hum.poly.c, hum.add)
names(hu.ma) <- "Outbreak_ID"

ma.hu <- inner_join(as.data.frame(hu.ma), hum.simple, by = "Outbreak_ID")
  #### OUT ####
humOB.bi <- biGenV(ma.hu)
humOB.occ <- occGenV(humOB.bi, "hum", c.mask)


#### Animal Index cases ####
an.src <- read.csv(file.path(data.source, "vIndex", "latest_animal_case.csv"))
an.simple <- an.src %>% dplyr::select(OUTBREAK_ID, Month.Start)
colnames(an.simple)[1] <- "Outbreak_ID"
 
 #### Polygons ####
an.poly <- readOGR(file.path(data.source, "vIndex", "animalORG"),
                   "animal_polygon")
an.poly.c <- SpatialPointsDataFrame(gCentroid(an.poly, byid = T),
                                    an.poly@data, match.ID = F)
names(an.poly.c) <- "Outbreak_ID"
 #### Points ####
an.pt <- readOGR(file.path(data.source, "vIndex", "animalORG"),
                   "animal_points")
an.pt <- an.pt[,1]
names(an.pt) <- "Outbreak_ID"
 #### masterFrame ####
an.ma <- rbind(an.poly.c, an.pt)

ma.an <- inner_join(as.data.frame(an.ma), an.simple, by = "Outbreak_ID")

 #### OUT ####
anOB.bi <- biGenV(ma.an)
anOB.occ <- occGenV(anOB.bi, "ann", c.mask)
