#### Viral Occurrence Munge ####
#### Re-work Oct 2017       ####
################################

source("R/helperFunctions.R")
library(rgdal);library(rgeos);library(raster);library(dplyr)

 ##Virus OCC functions
biGenV <- function(x){
  ### Funtion to create monthly occurrence/absence vectors for each record ###
  ## Argument: x - dataframe of events with location and breeding record
  empty <- as.data.frame(matrix(nrow=nrow(x), ncol=12)) 
  for(i in 1:nrow(empty)){
    for(j in 1:ncol(empty)){
      ifelse(j == x[i,]$"Month.Start",empty[i,j]<-1,empty[i,j]<-0)
    }}
  names(empty) <- paste0("OB",seq(1:12))
  out <- cbind(x,empty)
  return(out)
}

occGenV <- function(df, name, mask){
  ### Function to rasterize locations and generate monthly Occurrence/Absence dataframes ###
  ### Includes a 50Km buffer around each point to account for potential inpersion in source data.
  ## Arguments: 
  ## df - dataframe generated by biGenV()
  ## name - character string for naming purposes
  ## mask - name of the mask used
  coordinates(df) <- ~ x + y
  proj4string(df) <- proj4string(mask)
  out <- data.frame()
  for(i in 1:12){
    rr1 <- rasterize(df,mask, field= df[[paste0("OB",i)]], function(x, na.rm=FALSE) { sum(x>0, na.rm=na.rm) })
    rr2 <- crop(rr1,mask)
    rr3 <- mask(rr2,mask)
    df1 <- xyFromCell(rr3, cell = which(!is.na(rr3[])))
    df2 <- as.data.frame(cbind(df1,raster::extract(rr3,df1)))
    ifelse(i == 1, out <- df2, out <- as.data.frame(cbind(out,df2[,3])))
    colnames(out) <- c(colnames(out[,-ncol(out)]),paste0(name,i))
  }
  
  return(out)
}

viralRasterGen <- function(df, name, mask, out.dir = NULL){
  ##Function to create monthly rasters of viral occurrence 
  ##Arguments 
  # df <- df from bi.genV()
  # name <- name of it as a 3 letter code (generally hum or ann)
  # mask <- cropping mask to set it to
  # out.dir <- where it should be sent to if saved. 
  coordinates(df) <- ~ x + y
  proj4string(df) <- proj4string(mask)
  out <- list()
  for(i in 1:12){
    rr1 <- rasterize(df,mask, field= df[[paste0("OB",i)]], function(x, na.rm=FALSE) { sum(x>0, na.rm=na.rm) })
    rr2 <- crop(rr1,mask)
    rr3 <- mask(rr2,mask)
    names(rr3) <- paste0(name,i)
    out[[i]] <- rr3
  }
  out.stk <- do.call(stack, out)
  if(!is.null(out.dir)){
    writeRaster(out.stk, file.path(out.dir, "OB"), format = "GTiff",
                bylayer = T, suffix = "names", overwrite = T)
  }
  return(out.stk)
}

viralRasterGen0 <- function(df, name, z.mask, out.dir = NULL){
  ##Function to create monthly rasters of viral occurrence with 0 backs
  ##Arguments 
  # df <- df from bi.genV()
  # name <- name of it as a 3 letter code (generally hum or ann)
  # mask <- cropping mask to set it to with zero back 
  # out.dir <- where it should be sent to if saved. 
  
  out <- list()
  for(i in 1:12){
    r <- z.mask
    r[cellFromXY(z.mask,df[which(df[paste0("OB",i)] == 1),c("x","y")])] <- 1
    names(r) <- paste0(name,"0_",i)
    out[[i]] <- r
  }
  out.stk <- do.call(stack, out)
  if(!is.null(out.dir)){
    writeRaster(out.stk, file.path(out.dir, "OB"), format = "GTiff",
                bylayer = T, suffix = "names", overwrite = T)
  }
  return(out.stk)
}

## 
c.mask <- raster(file.path(data.source, "cropMask.tif"))
z.mask <- reclassify(c.mask, c(0,1,0))
wgs <- proj4string(c.mask)

#### human index cases ####
 ## note : bring in the Human_Index_30May. Contains 1 additional point over
 ## the source dataframe provided representing the Inkanamo outbreak
## UPDATE 12.2.018: additional entry for 2017 DRC outbreak
hum.src <- read.csv(file.path(data.source, "vIndex", "Human_Index_12_2_18.csv"))
hum.simple <- hum.src %>% dplyr::select(Outbreak_ID, Virus, Month.Start, Month.Start, Month.End , Class)
  
  #### Polygons ####
hum.poly <- readOGR(file.path(data.source, "vIndex", "humanORG"), 
                    "index_human_case_modified_polygon")
  ##addition of outbreak 32
drc.poly <- readOGR(file.path(data.source, "zone_ste_puc"), 
                    "Zone_Ste_Puc")
  ##pull out the zone sante
likati <- drc.poly[drc.poly$Nom_ZS_PUC == "Likati",]
lik.prj <- spTransform(likati, proj4string(hum.poly))
lik.prj$OUTBREAK <- 32

  ##bind
hum.poly <- rbind(hum.poly, lik.prj[,"OUTBREAK"])


 ## Extract centroids but maintain the data from the original obj
hum.poly.c <- SpatialPointsDataFrame(gCentroid(hum.poly, byid = T),
                                     hum.poly@data, match.ID = F)
  #### Points ####
 ## Still needs to be added here
hum.pts <- readOGR(file.path(data.source, "vIndex", "humanORG"), 
                   "index_human_case_modified_point")
new <- c(-0.616667, 20.433333, 31, 20.433333, -0.616667) ## outbreak 31
human.add <- rbind(as.data.frame(hum.pts), new)
coordinates(human.add) <- ~ coords.x1 + coords.x2
proj4string(human.add) <- CRS(wgs)
 ## Remove the lat and long cols
hum.add <- human.add[,3]

  #### masterFrame ####
hu.ma <- rbind(hum.poly.c, hum.add)
names(hu.ma) <- "Outbreak_ID"

ma.hu <- inner_join(as.data.frame(hu.ma), hum.simple, by = "Outbreak_ID")
  #### OUT ####
humOB.bi <- biGenV(ma.hu)
write.csv(humOB.bi, file.path(clean.dir,"humOB.PPM.csv"), row.names = F)
humOB.occ <- occGenV(humOB.bi, "hum", c.mask)
write.csv(humOB.occ, file.path(clean.dir,"humOcc.csv"), row.names = F)
viralRasterGen(humOB.bi, "hum", c.mask, file.path(clean.dir))
viralRasterGen0(humOB.bi, "hum", z.mask, file.path(clean.dir))

#### Animal Index cases ####
an.src <- read.csv(file.path(data.source, "vIndex", "Animal_Index_Jan2018.csv"))
an.simple <- an.src %>% dplyr::select(OUTBREAK_ID, Month.Start, Class)
colnames(an.simple)[1] <- "Outbreak_ID"
## remove the sero data that does not fit the analysis (ID 45:50)
an.simple <- an.simple[an.simple$Outbreak_ID %!in% 45:50,]
 
 #### Polygons ####
an.poly <- readOGR(file.path(data.source, "vIndex", "animalORG"),
                   "animal_polygon")
an.poly.c <- SpatialPointsDataFrame(gCentroid(an.poly, byid = T),
                                    an.poly@data, match.ID = F)
names(an.poly.c) <- "Outbreak_ID"
 #### Points ####
an.pt <- readOGR(file.path(data.source, "vIndex", "animalORG"),
                   "animal_points")
an.pt <- an.pt[,1]
names(an.pt) <- "Outbreak_ID"
 #### join dataFrames ####
an.ma <- rbind(an.poly.c, an.pt)
ma.an <- inner_join(as.data.frame(an.ma), an.simple, by = "Outbreak_ID")
 ##seperate bat and other animal cases
mam.an <- ma.an %>%
  filter(Class == 4)

bat.an <- ma.an %>%
  filter(Class == 1)


#### OUT ####
  ## animal points 
anOB.bi <- biGenV(mam.an)
write.csv(anOB.bi, file.path(clean.dir, "annOB.PPM.csv"), row.names = F)
anOB.occ <- occGenV(anOB.bi, "ann", c.mask)
write.csv(anOB.occ, file.path(clean.dir, "annOcc.csv"), row.names = F)
viralRasterGen(anOB.bi, "ann", c.mask, file.path(clean.dir))
viralRasterGen0(anOB.bi, "ann", z.mask, file.path(clean.dir))

  ## Host detection locations (hdl)
hdl.bi <- biGenV(bat.an)
write.csv(hdl.bi, file.path(clean.dir, "hdl.PPM.csv"), row.names = F)
hdl.occ <- occGenV(hdl.bi, "hdl", c.mask)
write.csv(hdl.occ, file.path(clean.dir, "hdlOcc.csv"), row.names = F)
viralRasterGen(hdl.bi, "hdl", c.mask, file.path(clean.dir))
viralRasterGen0(df = hdl.bi, name = "hdl",z.mask =  z.mask,out.dir =  file.path(clean.dir))
